### PR TITLE
BDV 10.0, major refactoring and support of image grids

### PR DESCRIPTION
**Pull request by tischi**
@K-Meech 
This does not use the BDV cards UI, but contains major refactoring to make that easier, if needed.
Could you have a look whether we could merge this already now?

### CODE REVIEW

**Comment by K-Meech** [comment]
@tischi I tried it out locally, and I noticed that the context menus are gone.
e.g. the 'load additional bookmarks...' option. Only the options for displayed segmentations are still there.

**Comment by tischi** [comment]
Does it work now?

**Comment by K-Meech** [comment]
That fixed the context menu!
I found another though - when you view a bookmark (e.g. Figure2C:Muscle Segmentation for the platy), it adds the raw data twice.

**Comment by tischi** [comment]
Good find!
Would you have time to look for the bug and then commit the fix to this branch?
Like this you will also have a chance to look at bit at the new structure of the code (still not perfect, but I hope a bit cleaner).

**Comment by K-Meech** [comment]
Sure - makes sense! I'll have some time tomorrow to look through

**Comment by K-Meech** [comment]
@tischi I fixed the bug with the bookmarks, and pushed it to this branch

**Comment by tischi** [comment]
Great!  Could we use this branch as our sort-of-master now for further developments?
Maybe until the whole grid view stuff is working including an image table?

**Comment by K-Meech** [comment]
Sure - sounds good!

**Comment by tischi** [comment]
@K-Meech I think it is working now. Could you try? There is this class in test/java/projects: OpenRemoteTomogramsBranch

**Comment by K-Meech** [comment]
It's not building for me - says there's no 'misc' in Metadata. Did you make some local changes to Metadata in imagej-utils?

**Comment by tischi** [comment]
Sorry, forgot to push changes to imagej-utils. Now it should be there.

**Comment by K-Meech** [comment]
Ok  - I see it now! There seems to be a problem with the colouring scheme though. e.g. Here I clicked on the top row of the table: it went to the correct position, but the tomogram is coloured purple, and not the green shown in the table.
Screenshot (261)

**Comment by tischi** [comment]
@K-Meech I think I fixed the bug.

**Comment by K-Meech** [comment]
Yes - it all works now!

**Pull request merged**
