### PR TITLE
Update dependency

### PR DESCRIPTION
**Pull request by KateMoreva**

### CODE REVIEW

**Review by constantinpape — APPROVED** [review]
Looks good! One question: Is the corresponding version of `bigdataviewer-imageloader` released to scijava.maven already? If not, can we release it first and update the dependency in the pom.xml, so that MoBIE can be build with the version from scijava?

**Comment by KateMoreva** [comment]
> Looks good! One question: Is the corresponding version of `bigdataviewer-imageloader` released to scijava.maven already? If not, can we release it first and update the dependency in the pom.xml, so that MoBIE can be build with the version from scijava?

Yes, it is released. MoBIE uses files from the latest version of  `bigdataviewer-imageloader` (after the reorganization of the repo )

**Comment by constantinpape** [comment]
> Yes, it is released. MoBIE uses files from the latest version of `bigdataviewer-imageloader` (after the reorganization of the repo )

Awesome. Then I think this is def. good to go; @tischi can you have another look at the changes and merge if you think everything is ok?

**Comment by KateMoreva** [comment]
> Looks good! One question: Is the corresponding version of `bigdataviewer-imageloader` released to scijava.maven already? If not, can we release it first and update the dependency in the pom.xml, so that MoBIE can be build with the version from scijava?

I also made a pre-release on Github.

**Comment by K-Meech** [comment]
@tischi @KateMoreva Can this PR already be merged?

**Pull request merged**
