### PR TITLE
Project creator 2.0

### PR DESCRIPTION
**Pull request by K-Meech**
Main changes:
- adds correct downsampling for segmentations
- splits export functionality from ExportImagePlusAsN5Plugin into a separate class: WriteImagePlusToN5
- removes hdf5 support
- changes default compression to gzip
- larger string fields in project creator
- Splits project creation into choosing a project name + project folder
- handles spaces in filepath
- refactored into more classes
- various small fixes

Still WIP:
- adding remote metadata

### CODE REVIEW

**Comment by K-Meech** [comment]
Alright - I think this is ready to merge now!
In addition to changes above, it adds:
- command for writing remote metadata to a project

@tischi - I changed XmlIoN5S3ImageLoader a bit, as the current toXml() wasn't giving the correct formatting

**Comment by tischi** [comment]
I will merge it, but could you please locally first check whether it merges well with the current master from today (because I just merged changes from @constantinpape and maybe there could be conflicts...)

**Comment by K-Meech** [comment]
I just checked - and all looks good!
I already made some changes to fit with @constantinpape (i.e. removing all the authentication fields)

**Comment by tischi** [comment]
You guys are faster then ⚡

**Comment by tischi** [comment]
Why is this PR still open? It is merged, isn't it?

**Comment by K-Meech** [comment]
It's merged! - but there's an old one: https://github.com/mobie/mobie-viewer-fiji/pull/184 that still needs to be closed

**Pull request merged**
