### PR TITLE
Add ome-zarr to project creator

### PR DESCRIPTION
**Pull request by K-Meech**
For https://github.com/mobie/mobie-viewer-fiji/issues/420, https://github.com/mobie/mobie-viewer-fiji/issues/311 and https://github.com/mobie/bigdataviewer-imageloader/issues/23

Main changes:
- adds support for bdv ome-zarr / ome-zarr to project creator
- adds a command for writing the current open image to ome-zarr (WriteOMEZARRCommand)
- adds a button to open the current project in MoBIE
- moves the addition of remote metadata from a command, to a button within the project creator
- adds some basic tests for the project creator (I'll hook these up to the CI once that is added too)
- Separated out opening SpimData into a separate class (as I need this for the project creator too) - 'SpimDataOpener' (@tischi I noticed that here you currently only use a sharedqueue for ome-zarr, not sure if you want this for all image types?)
- Added a dependency for a newer version of spim-data - as I need this fix: https://github.com/bigdataviewer/spimdata/pull/6

Note: this requires changes to the bigdataviewer-imageloader repo! (PR incoming)

### CODE REVIEW

**Comment by K-Meech** [comment]
New projectcreator ui:
Screenshot (345)

**Comment by tischi** [comment]
@K-Meech 

Thanks! This is looking great! I really like the `SpimDataOpener` class, maybe we could later even consider moving this to bdv-imageloader?

Could you please test that with all your changes 

1. one can still open the PlatyBrowser 

and

2.

That this code:

```
new MoBIE("/g/kreshuk/pape/Work/mobie/covid-if-project/data", MoBIESettings.settings().imageDataFormat( ImageDataFormat.OmeZarr ).view( "default_with_tables" ) );
```

yields this output?

image

If that's the case I think we can merge it.

And we should really soon write some tests for mobie....

**Comment by K-Meech** [comment]
Ok - great! I checked, and it's still possible to open the platybrowser.
I can't check the grid view, as I don't have access to the Kreshuk lab server. @constantinpape - is there any chance I could get added to the Kreshuk lab server? It would mean we don't have to move data around all the time... No worries if not.

**Comment by constantinpape** [comment]
> I can't check the grid view, as I don't have access to the Kreshuk lab server. @constantinpape - is there any chance I could get added to the Kreshuk lab server? It would mean we don't have to move data around all the time... No worries if not.

Sure! I just wrote a mail to IT.

In the meantime, there is a smaller version on the emcf server, if you open it you should see a similar view to Tischi's screenshot:
`/g/emcf/pape/covid-if-project`

**Comment by K-Meech** [comment]
@tischi I can't open the covid-if-project with this pr version, but also not with the current ```develop``` branch of mobie. It errors with: 
```
Exception in thread "main" java.lang.NullPointerException
	at de.embl.cba.mobie.transform.GridSourceTransformer.lambda$transform$0(GridSourceTransformer.java:40)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at de.embl.cba.mobie.transform.GridSourceTransformer.transform(GridSourceTransformer.java:40)
	at de.embl.cba.mobie.view.ViewManager.show(ViewManager.java:216)
	at de.embl.cba.mobie.MoBIE.openDataset(MoBIE.java:226)
	at de.embl.cba.mobie.MoBIE.openDataset(MoBIE.java:160)
	at de.embl.cba.mobie.MoBIE.<init>(MoBIE.java:96)
	at projects.OpenLocalCovidPlate.main(OpenLocalCovidPlate.java:18)
```
Do you get the same?

**Comment by tischi** [comment]
@K-Meech I never tried the one on S3 my best guess is that the JSON spec for the grid there is not up to date... (do you know @constantinpape)?

@K-Meech how could I run your branch on my computer? I guess the easiest for me would be if your branch as within the normal MoBIE repo and not in your fork....

**Comment by K-Meech** [comment]
This isn't the one on s3, it's the smaller local version on ```/g/emcf/pape/covid-if-project```. Maybe try just with the mobie develop branch first? It seems like its an issue there already, and not one with the stuff I added in the PR

**Comment by tischi** [comment]
Getting the same errors:

```
java.lang.NullPointerException
	at de.embl.cba.mobie.MoBIE.getImagePath(MoBIE.java:618)
	at de.embl.cba.mobie.MoBIE.openSourceAndConverter(MoBIE.java:306)
	at de.embl.cba.mobie.MoBIE.lambda$openSourceAndConverters$0(MoBIE.java:204)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
java.lang.NullPointerException
	at de.embl.cba.mobie.transform.GridSourceTransformer.lambda$transform$0(GridSourceTransformer.java:40)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at de.embl.cba.mobie.transform.GridSourceTransformer.transform(GridSourceTransformer.java:40)
	at de.embl.cba.mobie.view.ViewManager.show(ViewManager.java:216)
	at de.embl.cba.mobie.MoBIE.openDataset(MoBIE.java:226)
	at de.embl.cba.mobie.MoBIE.openDataset(MoBIE.java:160)
	at de.embl.cba.mobie.MoBIE.<init>(MoBIE.java:96)
	at projects.OpenLocalTest.main(OpenLocalTest.java:17)
```

**Comment by K-Meech** [comment]
Does that happen with ```/g/kreshuk/pape/Work/mobie/covid-if-project/data``` too? Or is it just the emcf version?

**Comment by tischi** [comment]
error only with emcf

**Comment by tischi** [comment]
It's fine to wait! Have a nice Weekend 🌴

**Comment by constantinpape** [comment]
Ok, I will also double check if I can find the error with the emcf data.

**Comment by tischi** [comment]
@K-Meech 

I found it:

```
To fetch a remote PR into your local repo,

git fetch origin pull/$ID/head:$BRANCHNAME

where $ID is the pull request id and $BRANCHNAME is the name of the new branch that you want to create. Once you have created the branch, then simply

git checkout $BRANCHNAME
```

**Comment by tischi** [comment]
I tested and it works.

**Pull request merged**
