### PR TITLE
Restructure package

### PR DESCRIPTION
**Pull request by K-Meech**
Restructures the project (to match the master branch)

@tischi I had issues with copying the actions files. Windows was somehow removing executable permissions (ah - I hate windows sometimes!) 
Could you merge this, then copy the '.github' folder on the master branch to the develop branch? If you could check everything inside the .github folder has read and execute permissions, that would be great too. Thanks!

### CODE REVIEW

**Comment by tischi** [comment]
Done via https://github.com/mobie/mobie-viewer-fiji/commit/ddd676e39005dc1e783cd82321b48eebdfd94dab

**Comment by K-Meech** [comment]
Great - thanks @tischi!

**Comment by tischi** [comment]
I am very curious though if the _rw_ rights that I set persist through an upload and download to github. Probably not, is it?

**Comment by K-Meech** [comment]
I don't know... But when I uploaded from my Windows computer, it seemed to persist the loss of execute permissions, like here: https://github.community/t/action-showing-permission-denied/134957/3 So I guess it must retain it somehow!?

**Pull request merged**
