### PR TITLE
Fixes #555

### LINKED ISSUE #555: Screenshot not working?
Giulia wrote an e-mail that the screenshot is not working for her in the CLEM example project.

### PR DESCRIPTION
**Pull request by tischi**
Fixes #555 and adds logging of normal vector viewer transform, which can be used to go "level" the view of the Platy.

### CODE REVIEW

**Comment by tischi** [comment]
@K-Meech could you have a look?

**Comment by tischi** [comment]
@K-Meech please don't merge yet, I had [an idea](https://github.com/mobie/mobie-viewer-fiji/pull/560/commits/e62a8ea6a14a43d7b4c66827e7cd460fcaafb185) that I still want to add...

**Comment by tischi** [comment]
@K-Meech I think this is ready to be merged now. Could you please have a look and merge and update?

**Review by K-Meech — COMMENTED** [review]
Hi @tischi - changes look good! But I see a few possible issues.

Not a big problem - but if you type in the box, rather than using the arrows, then the capture size[pixels] doesn't update until you click away. So might be a bit confusing...

Also, is the capture supposed to stay within the bounds of the viewport? When a take a screenshot of the default platybrowser view, it includes a lot of black space around it
Screenshot (380)
:

**Comment by tischi** [comment]
> Not a big problem - but if you type in the box, rather than using the arrows, then the capture size[pixels] doesn't update until you click away. So might be a bit confusing...

Yes, you have to press TAB or click away (I don't know how to improve this... any ideas?)

> Also, is the capture supposed to stay within the bounds of the viewport? When a take a screenshot of the default platybrowser view, it includes a lot of black space around 

OK, this looks like a :bug: that I introduced! I will fix it!

**Comment by K-Meech** [comment]
> Yes, you have to press TAB or click away (I don't know how to improve this... any ideas?)

I'm not sure either! I don't think it's a big problem though :)

**Comment by tischi** [comment]
@K-Meech is it now working?

**Comment by K-Meech** [comment]
Yes - that fixes it! Should I merge / update mobie-beta?

**Comment by tischi** [comment]
Yes, please ❤️

**Pull request merged**
