### PR TITLE
Adding tests

### PR DESCRIPTION
**Pull request by tischi**

### CODE REVIEW

**Comment by tischi** [comment]
@K-Meech I am working here on adding some test. This is not yet ready for merging.

**Comment by tischi** [comment]
@K-Meech could we merge this?

It is not really working because of [this](https://github.com/mobie/mobie-viewer-fiji/issues/520), but anyway.

I saw you also have tests. Could you please move them from to `src/main` `src/test/java/tests`?

**Comment by tischi** [comment]
@K-Meech you can have a look, but please do not merge yet as I am working on another issue that I would like to fix first.

**Comment by tischi** [comment]
@K-Meech OK, now it'd be ready to be merged.

**Comment by K-Meech** [comment]
@tischi I'm off sick today. I can take a look tomorrow. Otherwise, if you need it urgently, just go ahead!

**Comment by tischi** [comment]
Gute Besserung @K-Meech!!

**Pull request merged**
