### PR TITLE
Make randomColorSeed serialisable

### PR DESCRIPTION
**Pull request by tischi**
@K-Meech 

I implemented: `( ( CategoryColoringModel< ? > ) coloringModel ).getRandomSeed();`

I tried using this where we serialize the current view but I could not find it...

This class seems not to be used anywhere?! `ViewFromSourceAndConverterCreator`??

### CODE REVIEW

**Comment by tischi** [comment]
I found it, it should go into: `AnnotationDisplay`.

But should we then remove: `ViewFromSourceAndConverterCreator` ?

**Comment by K-Meech** [comment]
@tischi If it's not used anywhere, then go ahead and remove it. I think it was something you added anyway?

**Comment by tischi** [comment]
> If it's not used anywhere, then go ahead and remove it. I think it was something you added anyway?

not sure now; i'll leave it in, maybe there was some idea behind...

Otherwise could you have a look whether this PR looks good to you?

**Comment by K-Meech** [comment]
Can do! I'm making some videos for the paper at the moment, but I can look later

**Comment by tischi** [comment]
> Can do! I'm making some videos for the paper at the moment, but I can look later

Thanks! You will probably just have to look at the code, because I merged breaking changes of the JSON spec into this PR. Not sure, maybe the platybrowser will still open with this.

**Comment by K-Meech** [comment]
@tischi - on a very quick look, it seems good to me! But at the moment the version of imagej-utils you're using isn't available remotely (so the tests will fail). Could you release a new version of imagej-utils and use that instead?

**Comment by tischi** [comment]
> Could you release a new version of imagej-utils and use that instead?

I will do this later.

**Pull request merged**
