### PR TITLE
Json Test

### PR DESCRIPTION
**Pull request by tischi**
@constantinpape 

I cleaned up the code a bit.

I am confused now what actually the difference between the two validation methods is; in particular whether they us different libraries at all...would be cool if you could have a look!

### CODE REVIEW

**Comment by constantinpape** [comment]
Hey @tischi,
do you really want to merge this into `main`? Wouldn't it make more sense to make this PR onto `develop`?
(And I am happy to take a look later)

**Comment by tischi** [comment]
thanks for spotting this. changed to develop.

**Comment by constantinpape** [comment]
> I am confused now what actually the difference between the two validation methods is; in particular whether they us different libraries at all...would be cool if you could have a look!

So, here's what I understand from some quick checks: there are three relevant jsonschema libraries:
1. https://github.com/everit-org/json-schema <- this is the one Kimberly has used, but we should NOT use it because it's deprecated (see their comment in the README)
2. https://github.com/java-json-tools/json-schema-validator <- this is the one proposed by ChatGPT's artificial stupidity and that we have now added
3. https://github.com/erosb/json-sKema  <- this is the library suggested in the readme of 1. (So we are not using it right now, but maybe we should).

I will see if I can reactivate my IntelliJ and have a look later.

**Comment by constantinpape** [comment]
Hi @tischi,
I looked into this and we should use https://github.com/everit-org/json-schema after all. It supports what we need and the validation works correctly. (I think we did something wrong beforehand and that's why the spurious `name` didn't trigger the error).

I pushed a new commit now and the validation is working properly. And this shows that we still have the following spec related issues: (see full json that causes this below):
1. `"color": "255-255-255-255"`: this must now be `r=255,g=255,b=255,a=255`
2. `"overlayNames":false`: this is not part of the spec

Regarding 1: I am not sure where this is validated, can you fix it?
Regarding 2: I suggest we make this transient for now so that it's not serialized. Let's resolve #1013 first before discussing how we add this to the spec (because maybe we'll need to add some extra stuff for this).

```json
{"sources":{"testImage":{"image":{"imageData":{"bdv.n5":{"relativePath":"images/bdv-n5/testImage.xml","channel":0}}}}},"is2D":false,"defaultLocation":{"position":[0,0,0],"timepoint":0},"views":{"default":{"isExclusive":true,"sourceDisplays":[{"imageDisplay":{"showImagesIn3d":false,"visible":true,"sources":["testImage"],"color":"255-255-255-255","contrastLimits":[0,255],"name":"testImage","opacity":1}}],"overlayNames":false,"uiSelectionGroup":"bookmark"},"testImage":{"isExclusive":false,"sourceDisplays":[{"imageDisplay":{"showImagesIn3d":false,"visible":true,"sources":["testImage"],"color":"255-255-255-255","contrastLimits":[0,255],"name":"testImage","opacity":1}}],"overlayNames":false,"uiSelectionGroup":"testGroup"}}}
```

**Comment by tischi** [comment]
1. see https://github.com/mobie/mobie-viewer-fiji/issues/924
2. changed to transient

**Comment by constantinpape** [comment]
Can you push the changes here? The tests should pass then. (If not I will take another look)

**Comment by tischi** [comment]
I changed it, but it still fails:

```
Json Schema validation failed:
#/sources/testImage: #: only 1 subschema matches out of 2
#/sources/testImage: #: 0 subschemas matched instead of one
```

I don't know what that means...

**Comment by constantinpape** [comment]
@tischi: there is one problem left now:
It serializes this for the image source: `"testImage":{"image":{"imageData":{"bdv.n5":{"relativePath":"images/bdv-n5/testImage.xml","channel":0}}}}`.
However, we don't have channel in the spec for `bdv.n5`, only for `ome.zarr`.

So we either:
- do not serialize channel for `bdv.n5`
- add it to the spec for `bdv.n5` (for all sources)?

As far as I know the reason that we only have it for `ome.zarr` is that this is the only image format where we actually support multiple channels.

**Comment by tischi** [comment]
I would say let's add it for all image sources to the spec.

from the Java code of `StorageLocation`:

```
	// the image data model in MoBIE is single channel,
	// and thus one needs to subset a potentially
	// multi-channel image data source.
	//
	// as data is opened as {@code SpimData}
	// the {@code channel} can also refer to a setup, which
	// does not need to be a fluorescence channel, but could be some
	// entirely other image, e.g. in CZI or LIF files
	// 
	// also the BDV XML based files can contain multiple "setups"
	// which can be chosen from via the {@code channel} field
	//
	// historically, we only had fluorescence channels, 
	// and thus the name of the variable is "channel" and cannot 
	// readily be changed because we use in the MoBIE JSON spec
	public Integer channel = 0; // only for images
```

**Comment by constantinpape** [comment]
Hey @tischi,
I have updated the spec now and the image tests pass. However the segmentation tests still fail because of this:
```"tableData":{"tsv":{"relativePath":"tables/testImage","channel":0}
```
I.e. the `channel` attribute is also serialized for `tableData`. This doesn't make sense and you will need to fix it.

**Comment by constantinpape** [comment]
> That's right, and I somehow always thought the reason I am doing this is that I need to do this because of the spec. I could change this, and it would be nice but a lot of refactoring.
> 
>     * [ ]  I think we should open a new issue about changing this in the code

Your change works for now (so indeed looks like setting it to `null` will not serialize it), so it's up to you if you want to refactor it.

> However for me the tests still fail.

The remaining problem is that the `segmentationDisplay` serializes the `blendingMode` property. In the spec we only have this for `imageDisplay`. I think this goes back to a discussion some time ago where we said that the blending mode is not needed for segmentations because we only have one reasonable choice for it. So again two ways to fix it:
- don't serialize the `blendingMode` for segmentation displays
- or we add it to the spec for segmentation displays (but I would prefer to do this only if it actually makes sense to have it there)

> Can you somehow change the code such that it prints something as to why the tests fail?

Sorry, I don't really know how to do this. The problem is that the errors from the java jsonschema checker are somehow nested, and [this](https://github.com/mobie/mobie-viewer-fiji/blob/jsontest/src/test/java/org/embl/mobie/lib/create/JSONValidator.java#L57-L59) only prints the first level (so we only see the unhelpful error messages). I am not sure how to change it to print this recursively. 

For now, I have been copying the json representation from debug and pasted it into a script to validate it via the python jsonschema library to get the proper errors.

**Comment by tischi** [comment]
I did the same trick of removing the default value, does it work?

I think here I could also move the field to just `ImageDisplay` but I am not sure we may need it also for the `AnnotationDisplay` at some point, so if possible I would leave it also there....

**Comment by constantinpape** [comment]
Your changes didn't work, the `blendingMode` is still serialized (and consequently the tests still fail).

**Comment by tischi** [comment]
now?

**Comment by constantinpape** [comment]
> now?

Yes, now it works; the tests pass.

This is good to go from my end now.

**Comment by martinschorb** [comment]
Hi,

I just realized that also MoBIE's "Save Current View" functionality has updated from putting "name" fields (violating the current spec) into views. However, it now puts adds another field that does not validate correctly:`Property 'overlayNames' is not allowed`

It is doing that even when I remove all of these properties from the source dataset. And it then adds it to all views of the dataset.

Like here:
https://github.com/mobie/centriole-tomo-datasets/blob/9041c0f52424a5a257101941afd10f5e13153396/data/tomo/dataset.json#L50 

Or am I using an outdated spec (current `master`)?

**Comment by tischi** [comment]
@martinschorb I will merge this now and upload to MoBIE-beta later today. Then you can check again. If the issue persists, please open an issue.

**Pull request merged**
