### PR TITLE
View loading and saving

### PR DESCRIPTION
**Pull request by K-Meech**
This adds:
- loading additional views from the project (github, s3 or file) or file system
- saving additional views to the project (github or file) or file system

Also needs changes to imagej-utils (PR to come)

@tischi There are quite a lot of merge conflicts now, as I think you're in the process of removing the SourceTransformerSupplier / SourceDisplaySupplier. Let me know when that's stable, and I'll adapt this PR again!

### CODE REVIEW

**Comment by tischi** [comment]
> There are quite a lot of merge conflicts now, as I think you're in the process of removing the SourceTransformerSupplier / SourceDisplaySupplier. Let me know when that's stable, and I'll adapt this PR again!

Should be stable now (at least it is working). 
Thank you for adapting your PR ❤️

**Comment by K-Meech** [comment]
I updated the PR!
Main changes:
- Added a custom serialiser to your new classes

**Comment by tischi** [comment]
Sorry, I was faster than you :-)
Could you please fix the new merge conflicts again?
You can then just merge it yourself!

**Comment by K-Meech** [comment]
Alright - third time lucky! I've fixed the PR again; I'll merge it now :)

**Comment by tischi** [comment]
Thanks! Sorry for that!

**Pull request merged**
