### PR TITLE
Open projects from s3

### PR DESCRIPTION
**Pull request by constantinpape**
Towards opening projects directly from s3, see #182.

First change: allows opening projects without the "data" subfolder. This is important for s3 projects, where we don't always follow this convention; and generally nice to have.
I couldn't fully test it due to #209, but I think this part should work.

The next steps toward opening s3 projects directly is using the s3 api for fetching the `datasets.json` and other files (pure http access is not supported in s3, or a least not trivially).

@tischi:
- I think the `fileOrUrlExists` function is pretty useful; do you have something like this implemented somewhere else already? If not, should it be refactored, e.g. into FileAndUrlUtils?
- What's the best strategy for integrating the s3 api (https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/examples-s3.html)? Should this also go int FileAndUrlUtils? Somewhere else?

### CODE REVIEW

**Comment by constantinpape** [comment]
> Wow! @constantinpape writing Java code! This is amazing!!
> :-)

It's just weird C++ syntax ;).



> Let's also chat about these things today.

Sounds good.

**Comment by constantinpape** [comment]
This works now.
mobie-from-s3
It depends on the changes in https://github.com/tischi/imagej-utils/pull/36

**Comment by constantinpape** [comment]
Now also opening tables etc. works and I think this is ready to be merged once https://github.com/tischi/imagej-utils/pull/36 gets merged.
The only thing not supported yet is reading from buckets with credentials, see https://github.com/tischi/imagej-utils/pull/36#issuecomment-797506749 for details.

**Comment by tischi** [comment]
Cool! Thanks so much!

**Pull request merged**
