### PR TITLE
Diverse refactoring

### PR DESCRIPTION
**Pull request by tischi**
Here's some refactoring that I did / want to do.

@K-Meech @constantinpape 
You could have a brief look through the points if you want.
I don't think there is anything too critical though.

---
SourceDisplay interface:

- [ ] Add getMask()?
- [ ] Maybe getRealInterval would be sufficient?
  - This would allow checking whether a SourceDisplay is currently visible in BDV in terms of intersecting with the current view (without checking all the individual sources, which may be expensive)
  - For this to work correctly, the SourceDisplay would need to listen whether the Transformation of one of the containing sources was changed and then accordingly update the mask

--- 

- [X] Create a SliceView interface and AbstractSliceView
- [ ] SliceView and AbstractSliceView could contain the getRealInterval() method (s.a.) to indicate the union location of all sources that are displayed in this SliceView. Then SourceDisplay.getSliceView().getRealInterval() would be used.
- [X] Add close() method; maybe just one implementation in AbstractSliceView needed?
- [X] AbstractSliceView constructor should not take bdvHandle, but the SliceViewer, which could implement show(sac), which can be used to show sources and do common things.

---

Change names:

- [x] AnnotatedRegionDisplay -> AnnotationDisplay ?
- [x] AnnotatedSourceDisplay -> RegionDisplay ?
- [x] SegmentationSourceDisplay -> SegmentationDisplay ?
- [x] ImageSourceDisplay -> ImageDisplay ?

---

- [x] AnnotatedRegionDisplay.getSources() currently returns all annotated sources. Is this correct? In fact, AnnotatedRegionDisplay only displays one Source, namely the `SourceAndConverter< IntType > sourceAndConverter` which implements the overlay. I thus think it is wrong; also could not see an issue in the code that uses his method.

--- 

- [x] MoBIEHelper.containsAtLeastOne could be replaced by some Java 8 code.

---

In ViewManager, there is the code following:

`// remove any sourceTransformers, where none of its relevant 'sources' are displayed
...
`

- [x] Refactor into a method called updateCurrentSourceTransformers?
@K-Meech, OK?

--- 

- [x] BdvGlobalMousePositionProvider --> GlobalMousePositionProvider
- [x] BdvCircleOverlay --> CircleOverlay

---

- [X] PublishedProjectsCreator --> PublishedProjects

--- 

PublishedProjectsCreator:

- [X] Create method for each project for better readability.

---

- [x] *Helpers --> *Helper 
- [x] *Utils --> *Helper

In several places (to be consistent, also with bdv-pl)

---

- [X] ThreadUtils --> MultiThreading
- [X] ThreadUtils: n => num 

---

- [X] `AdditionalViews` and `AdditionalViewsLoader`: Move up one level up in package structure and delete `additionalviews` package.

---

- [x] OMEZarrViewer: Move up two levels up to org.embl.mobie

---

- [x] view.saving.* ---> view.save.*

---

- [x] ViewsSaver --> ViewSaver, @K-Meech, OK?

### CODE REVIEW

**Comment by K-Meech** [comment]
Sounds good to me @tischi ! For renaming the displays, maybe it would be best to match the names in the json schema as much as possible? (https://github.com/mobie/mobie.github.io/blob/master/schema/view.schema.json)

**Comment by constantinpape** [comment]
I just had a brief look at the changes and they overall look good to me.

> For renaming the displays, maybe it would be best to match the names in the json schema as much as possible? 

I agree that if we rename here we should also consider renaming in the jsoschema. And I also think that the new names are better. But renaming in the schema means that we also need to update all projects and that would be a bit of work for me and I would only have time for it maybe middle of next week. (and when we do it we should include the change from #681).

**Comment by constantinpape** [comment]
@tischi Do you still want to go ahead with the renaming? I could probably implement this and change it for our projects on Wednesday or Thursday.

**Comment by tischi** [comment]
> Do you still want to go ahead with the renaming?

Yes, do the names that I proposed sound good?

**Comment by constantinpape** [comment]
> Yes, do the names that I proposed sound good?

Yep, sounds good. I will go ahead and implement this and ping you once there's a branch to try it on.

**Comment by tischi** [comment]
I am done with the Refactoring.
I moved the open points to https://github.com/mobie/mobie-viewer-fiji/issues/698 and will work on it in https://github.com/mobie/mobie-viewer-fiji/pull/699 once this PR is merged.

@K-Meech 
Again, too many code changes to review this...sorry...I should get better at this...
All tests pass, so it should be fine.
Maybe play around with it a bit.
Let me know if we can merge.

**Pull request merged**
