### PR TITLE
project creator api javadoc

### PR DESCRIPTION
**Pull request by K-Meech**
For https://github.com/mobie/mobie-viewer-fiji/issues/591
Add javadoc for main project creator api functions

(I'll also update the mobie.github.io soon to give more examples)

### CODE REVIEW

**Comment by tischi** [comment]
Looks good @K-Meech !

One thought (@constantinpape): Do we actually support having images of mixed image formats in the same dataset? I have a feeling we specify on the project.json level the image format that we want to use throughout when loading images...

**Comment by K-Meech** [comment]
I think that there can be multiple image formats in the same dataset (in terms of the spec), but this can't actually be opened in MoBIE at the moment, as it automatically chooses one format here: https://github.com/mobie/mobie-viewer-fiji/blob/develop/src/main/java/org/embl/mobie/viewer/MoBIE.java#L116 ?

**Comment by tischi** [comment]
I would suggest to modify that project creator to just choose one image format in the beginning and then stick with it, what do you think? That would also make the API and UI easier.

Unless someone sees actual use-cases for mixed image data formats within a project?

@martinschorb @constantinpape ?

**Comment by martinschorb** [comment]
> Unless someone sees actual use-cases for mixed image data formats within a project?

If you have two large volumes that have been part of a MoBIE project before and were converted to different formats - maybe because they have been collected at different institutes, one doing the X-Ray and one doing EM or Light Microscopy - and you then want to create one MoBIE project with both of them registered.

**Comment by tischi** [comment]
Fair point @martinschorb.
OK, maybe then we leave it flexible (and, once necessary also implement opening such mixed datasets in MoBIE, I don't feel this should be a problem.......)

**Comment by K-Meech** [comment]
Sounds good to me! I think leaving it flexible for now is fine. I'll go ahead and merge this.

**Pull request merged**
