### PR TITLE
Write views s3

### PR DESCRIPTION
**Pull request by tischi**
Needs https://github.com/mobie/mobie-io/pull/81

@K-Meech Could you please have a look at the changes I made to the `DatasetJsonParser`. Is that too naive? Looks somehow to easy to be true...

### CODE REVIEW

**Comment by KateMoreva** [comment]
@tischi, are you sure that the PR should be to the `main`, not to the `develop`? :)

**Comment by tischi** [comment]
changed it to be against `develop`.

**Review by K-Meech — COMMENTED** [review]
@tischi - I think that should work! Although, in ```saveDataset```, you would need to find another way to ```setIndent```. Gson uses tab by default, but we changed this to 2 spaces to match Constantin's python code. Maybe this can be set directly in the Gson though, rather than on the JsonWriter?

**Comment by tischi** [comment]
@constantinpape @K-Meech 

> Gson uses tab by default, but we changed this to 2 spaces to match Constantin's python code.

looks tricky: https://github.com/google/gson/issues/1279

I think I would just do this: `gsonInstancePretty.toJson(object).replaceAll("  ", "\t");`

**Comment by K-Meech** [comment]
@tischi - if the default for pretty printing is 2 spaces, then that's great! 2 spaces is what we want, not tabs :)

**Comment by tischi** [comment]
Can we merge now?

**Comment by constantinpape** [comment]
> Can we merge now?

No objection from the code side on my end; but could you check why the test is failing?

**Comment by tischi** [comment]
Could not find the new mobie-io dependency yet.

**Pull request merged**
