### PR TITLE
Source annotation display

### PR DESCRIPTION
**Pull request by tischi**
@constantinpape @K-Meech 
I did all the changes to read the new SourceAnnotationDisplay. 
It was quite some work, but I think it is much cleaner now.
The serialization is still missing...
And there will be bugs for sure, which I will find once I can test it on an example...

### CODE REVIEW

**Comment by tischi** [comment]
@K-Meech This seems to work now:
```
new MoBIE("https://github.com/mobie/zebrafish-lm-datasets", MoBIESettings.settings().gitProjectBranch( "new-grid-spec" ).imageDataFormat( ImageDataFormat.BdvN5S3 ) );
```
If you think it's fine, please merge it.

**Comment by tischi** [comment]
@K-Meech 
I had quite some merge conflicts with master. In this branch below is giving an error:

```
public class OpenRemoteRawOmeZarr {
    public static void main(String[] args) throws IOException {
        final ImageJ imageJ = new ImageJ();
        imageJ.ui().showUI();
        new MoBIE("https://s3.embl.de/i2k-2020/project-bdv-ome-zarr", MoBIESettings.settings().imageDataFormat(ImageDataFormat.OmeZarr));
    }
}
```

This needs the latest additions by @KateMoreva. Obviously I screwed something up during the merging. Not sure yet what....

**Comment by tischi** [comment]
@KateMoreva could you please try to get this branch running on your computer?
you will need to download some repos and compile them (see SNAPSHOT versions in the pom).

**Comment by KateMoreva** [comment]
> @K-Meech
> I had quite some merge conflicts with master. In this branch, running below code is giving an error:
> 
> ```
> public class OpenRemoteRawOmeZarr {
>     public static void main(String[] args) throws IOException {
>         final ImageJ imageJ = new ImageJ();
>         imageJ.ui().showUI();
>         new MoBIE("https://s3.embl.de/i2k-2020/project-bdv-ome-zarr", MoBIESettings.settings().imageDataFormat(ImageDataFormat.OmeZarr));
>     }
> }
> ```
> 
> This needs the latest additions by @KateMoreva. Obviously I screwed something up during the merging. Not sure yet what....

I had  #https://github.com/mobie/mobie-viewer-fiji/issues/348

**Comment by KateMoreva** [comment]
> @KateMoreva could you please try to get this branch running on your computer?
> you will need to download some repos and compile them (see SNAPSHOT versions in the pom).


For now, I have `cannot serialize de.embl.cba.mobie.bdv.MobieBdvSupplier;` error.

**Comment by tischi** [comment]
@KateMoreva 

1. are you sure you pulled the latest version?
2. can you try to do `mvn compile` in the terminal? does that help?

**Comment by KateMoreva** [comment]
> @KateMoreva
> 
> 1. are you sure you pulled the latest version?
> 2. can you try to do `mvn compile` in the terminal? does that help?

I have the latest version, just needed to reload the project and mvn compile several times, some problems with the maven.

**Comment by tischi** [comment]
> I have the latest version, just needed to reload the project and mvn compile several times, some problems with the maven.

I had the same issues 😃 

> OpenRemoteRawOmeZarr works fine.

Surprising, does not for me...

I am getting:

```
Exception in thread "pool-2-thread-1" java.lang.NullPointerExceptionFetched 0 image source(s) in 494 ms, using 8 thread(s).

	at bdv.spimdata.WrapBasicImgLoader.<init>(WrapBasicImgLoader.java:110)
	at bdv.spimdata.WrapBasicImgLoader.wrapImgLoaderIfNecessary(WrapBasicImgLoader.java:68)
	at sc.fiji.bdvpg.sourceandconverter.importer.SourceAndConverterFromSpimDataCreator.createSourceAndConverters(SourceAndConverterFromSpimDataCreator.java:76)
	at sc.fiji.bdvpg.sourceandconverter.importer.SourceAndConverterFromSpimDataCreator.<init>(SourceAndConverterFromSpimDataCreator.java:61)
	at de.embl.cba.mobie.MoBIE.getSourceAndConverter(MoBIE.java:272)
	at de.embl.cba.mobie.MoBIE.lambda$openSourceAndConverters$0(MoBIE.java:162)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at de.embl.cba.mobie.ui.UserInterfaceHelper.createImageDisplaySettingsPanel(UserInterfaceHelper.java:283)
	at de.embl.cba.mobie.ui.UserInterface.createDisplaySettingPanel(UserInterface.java:102)
	at de.embl.cba.mobie.ui.UserInterface.addSourceDisplay(UserInterface.java:93)
	at de.embl.cba.mobie.view.ViewerManager.showSourceDisplay(ViewerManager.java:260)
	at de.embl.cba.mobie.view.ViewerManager.show(ViewerManager.java:216)
	at de.embl.cba.mobie.MoBIE.openDataset(MoBIE.java:186)
	at de.embl.cba.mobie.MoBIE.openDataset(MoBIE.java:119)
	at de.embl.cba.mobie.MoBIE.<init>(MoBIE.java:88)
	at projects.OpenRemoteRawOmeZarr.main(OpenRemoteRawOmeZarr.java:14)
```

**Comment by KateMoreva** [comment]
> > I have the latest version, just needed to reload the project and mvn compile several times, some problems with the maven.
> 
> I had the same issues 
> 
> > OpenRemoteRawOmeZarr works fine.
> 
> Surprising, does not for me...
> 
> I am getting:
> 
> ```
> Exception in thread "pool-2-thread-1" java.lang.NullPointerExceptionFetched 0 image source(s) in 494 ms, using 8 thread(s).
> 
> 	at bdv.spimdata.WrapBasicImgLoader.<init>(WrapBasicImgLoader.java:110)
> 	at bdv.spimdata.WrapBasicImgLoader.wrapImgLoaderIfNecessary(WrapBasicImgLoader.java:68)
> 	at sc.fiji.bdvpg.sourceandconverter.importer.SourceAndConverterFromSpimDataCreator.createSourceAndConverters(SourceAndConverterFromSpimDataCreator.java:76)
> 	at sc.fiji.bdvpg.sourceandconverter.importer.SourceAndConverterFromSpimDataCreator.<init>(SourceAndConverterFromSpimDataCreator.java:61)
> 	at de.embl.cba.mobie.MoBIE.getSourceAndConverter(MoBIE.java:272)
> 	at de.embl.cba.mobie.MoBIE.lambda$openSourceAndConverters$0(MoBIE.java:162)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)
> Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
> 	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
> 	at java.util.ArrayList.get(ArrayList.java:433)
> 	at de.embl.cba.mobie.ui.UserInterfaceHelper.createImageDisplaySettingsPanel(UserInterfaceHelper.java:283)
> 	at de.embl.cba.mobie.ui.UserInterface.createDisplaySettingPanel(UserInterface.java:102)
> 	at de.embl.cba.mobie.ui.UserInterface.addSourceDisplay(UserInterface.java:93)
> 	at de.embl.cba.mobie.view.ViewerManager.showSourceDisplay(ViewerManager.java:260)
> 	at de.embl.cba.mobie.view.ViewerManager.show(ViewerManager.java:216)
> 	at de.embl.cba.mobie.MoBIE.openDataset(MoBIE.java:186)
> 	at de.embl.cba.mobie.MoBIE.openDataset(MoBIE.java:119)
> 	at de.embl.cba.mobie.MoBIE.<init>(MoBIE.java:88)
> 	at projects.OpenRemoteRawOmeZarr.main(OpenRemoteRawOmeZarr.java:14)
> ```

Can you open this file from the master branch?

**Comment by tischi** [comment]
> Can you open this file from the master branch?

yes

**Comment by tischi** [comment]
maybe also some maven stuff....

@K-Meech can you run `OpenRemoteRawOmeZarr` in this branch?

**Comment by tischi** [comment]
Weird... I did `mvn clean compile` and it still fails for me with the same error...

**Comment by K-Meech** [comment]
@tischi - I'm on holiday until Thursday, so I won't be able to check. I can have a look Thursday/Friday though :)

**Comment by KateMoreva** [comment]
> Weird... I did `mvn clean compile` and it still fails for me with the same error...



> Weird... I did `mvn clean compile` and it still fails for me with the same error...


I think the problem is that one method somehow was merged in the wrong way.

**Comment by KateMoreva** [comment]
Does everything work fine after the method fix?

**Comment by tischi** [comment]
@KateMoreva Great! It works now!
I tried merging with master, but I got the same mess as before...
I don't know why the merging is so hard.
Could you please try to merge this branch with the current master?
And then just merge it also here on github?

**Comment by KateMoreva** [comment]
> @KateMoreva Great! It works now!
> I tried merging with master, but I got the same mess as before...
> I don't know why the merging is so hard.
> Could you please try to merge this branch with the current master?
> And then just merge it also here on github?

Great! Yes, sure, but I think I will still be unable to push changes. Would it be ok, if I post the needed version of MoBIE.jave here?

**Comment by tischi** [comment]
@constantinpape I can't figure out how to grant @KateMoreva access to push to this branch, can you?
She should also get merge rights.

**Comment by constantinpape** [comment]
@KateMoreva I upgraded you to a Maintainer for this repository, you should be able to directly push to this branch now.

**Comment by KateMoreva** [comment]
> @KateMoreva I upgraded you to a Maintainer for this repository, you should be able to directly push to this branch now.

Thank you!

**Comment by KateMoreva** [comment]
> @KateMoreva Great! It works now!
> I tried merging with master, but I got the same mess as before...
> I don't know why the merging is so hard.
> Could you please try to merge this branch with the current master?
> And then just merge it also here on github?

The brunch was updated and has no conflicts with the `master` now. Please check that you can run `OpenRemoteBdvOmeZarr` and all your new functionality works as it should :)

**Comment by tischi** [comment]
❤️

**Pull request merged**
