### PR TITLE
Volume rendering resolution

### PR DESCRIPTION
**Pull request by tischi**
@K-Meech 

Does this PR [fix this](https://github.com/mobie/mobie-viewer-fiji/issues/323)?

Don't merge yet, I also want to make the image volume rendering configurable...

### CODE REVIEW

**Comment by K-Meech** [comment]
Yes - that fixes it, thanks!

**Comment by tischi** [comment]
@K-Meech Can you play a bit with this? I added a right-click menu for changing the image volume rendering resolution...

**Comment by K-Meech** [comment]
Looks good! Although, it seems like you can't enter decimal values, only whole numbers? Also, you have the units 'um' on both the segments and image volume rendering menus. I guess this is actually whatever physical unit the project is using? E.g. I know some people use nanometer for their projects so it might be a bit confusing if it isn't really converting to microns.

**Comment by tischi** [comment]
Thanks @K-Meech !

Better now?

**Review by K-Meech — APPROVED** [review]
Looks good! Thanks @tischi! Go ahead and merge it :)

**Pull request merged**
