### PR TITLE
Make compatible with mobie.io 1.1.0

### PR DESCRIPTION
**Pull request by tischi**

### CODE REVIEW

**Review by KateMoreva — APPROVED** [review]
Ok, I can continue with this.

**Comment by tischi** [comment]
@KateMoreva 
I finished it; this works now with mobie-io `1.1.0`.
I will wait a bit for your review, but if you don't have time, that's no problem, I would just merge later today.

**Comment by KateMoreva** [comment]
> @KateMoreva I finished it; this works now with mobie-io `1.1.0`. I will wait a bit for your review, but if you don't have time, that's no problem, I would just merge later today.

Ok, I''ll then just merge it to the https://github.com/mobie/mobie-viewer-fiji/pull/564, which contains these changes.

**Comment by tischi** [comment]
> Ok, I''ll then just merge it to the #564, which contains these changes.

Ah sorry, I did not find this...
I think I did now everything here; so probably no need to merge.
Sorry for overlooking this.

**Comment by tischi** [comment]
@KateMoreva could you please have a look at my changes and check whether I overlooked something that you did in https://github.com/mobie/mobie-viewer-fiji/pull/564? Sorry again, for doing the work twice.

**Comment by KateMoreva** [comment]
> @KateMoreva could you please have a look at my changes and check whether I overlooked something that you did in #564? Sorry again, for doing the work twice.

I am not sure about commit 7fd56eab71cf9d71ffa7cd0a8e278c1fd6a0dd7d. It seems that there would be problems with data opening.

**Comment by tischi** [comment]
> I am not sure about commit 7fd56ea. It seems that there would be problems with data opening.

It seems to work...also `mvn test` runs without an error.
What specifically were you worried about?

**Comment by KateMoreva** [comment]
> > I am not sure about commit [7fd56ea](https://github.com/mobie/mobie-viewer-fiji/commit/7fd56eab71cf9d71ffa7cd0a8e278c1fd6a0dd7d). It seems that there would be problems with data opening.
> 
> It seems to work...also `mvn test` runs without an error. What specifically were you worried about?

I was worried about S3 variants. But it is nice that everything works fine :+1:

**Pull request merged**
