### PR TITLE
Issue720; 3D viewer crashed on MacOs

### PR DESCRIPTION
**Pull request by tischi**
@K-Meech 

1. Does that compile for you? I followed those instructions: https://forum.image.sc/t/icy-crashes-when-clicking-3d-view-macos-catalina/40628/21
2. If it does not compile for you, maybe we have to also add the corresponding jars for Windows.

### CODE REVIEW

**Comment by K-Meech** [comment]
This doesn't compile for me 
```
Cannot resolve org.jogamp.jogl:jogl-all-natives-macosx-universal:2.4.0-rc-20200307 
```
Doe I have to manually put these files into ```${project.basedir}/src/main/resources/```?

**Comment by tischi** [comment]
The .jar files were excluded from git. I added them. Could you please pull and try again?

**Comment by tischi** [comment]
OK, progress :-)

I guess that means that we have to add also the windows jars and the corresponding import statements in the pom.

Could you give this a try, following the instructions by Tobias here?
https://forum.image.sc/t/icy-crashes-when-clicking-3d-view-macos-catalina/40628/21

Files for download are here:
https://jogamp.org/deployment/archive/rc/v2.4.0-rc-20200307/jar/

Should be added to: `src/main/resources`

We probably need to add the Windows equivalents of those two:

```
		<dependency>
			<groupId>org.jogamp.jogl</groupId>
			<artifactId>jogl-all-natives-macosx-universal</artifactId>
			<version>2.4.0-rc-20200307</version>
			<scope>system</scope>
			<systemPath>${project.basedir}/src/main/resources/jogl-all-natives-macosx-universal.jar</systemPath>
		</dependency>
		<dependency>
			<groupId>org.jogamp.gluegen</groupId>
			<artifactId>gluegen-rt-natives-macosx-universal</artifactId>
			<version>2.4.0-rc-20200307</version>
			<scope>system</scope>
			<systemPath>${project.basedir}/src/main/resources/gluegen-rt-natives-macosx-universal.jar</systemPath>
		</dependency>
```

**Comment by tischi** [comment]
@K-Meech 

Would you have time to look at this today? This prevents me from running  the tests on my computer. 

Should I try adding the windows dependencies for you?

**Comment by K-Meech** [comment]
@tischi Today is super busy for me, so I'm not sure I'll be able to. I'll have time tomorrow, if that's not too late.

**Comment by tischi** [comment]
Tomorrow is fine. 
I can then for now rely on the test in the CI.

**Comment by K-Meech** [comment]
@tischi - adding the windows dependencies worked. I added them directly to this branch, so you should be able to just go ahead and merge.

**Comment by tischi** [comment]
@K-Meech The tests have failed. I assume that we also need to add the respective Linux versions.
Could you have a look?

**Comment by K-Meech** [comment]
I'll take a look

**Comment by K-Meech** [comment]
I'll wait until the version issues are fixed first. This currently fails for me because of the version of mobie-io vs bigdataviewer-core on this branch

**Comment by tischi** [comment]
I merged the latest develop. 
Does it work now?

**Comment by K-Meech** [comment]
@tischi - I can't build it at the moment due to the version of imagej-utils (0.6.7-SNAPSHOT) not being available remotely. I tried building from the imagej-utils repo master branch, and this was also failing for me.

**Comment by K-Meech** [comment]
It still won't build for me - it complains about not being able to find ```IOHelper```. Does this branch build for you?

**Comment by tischi** [comment]
I cut a new mobie-io release and this branch now depends on it.
Better?
Sorry for the back and forth, so many changes...

**Comment by K-Meech** [comment]
@tischi - yes that works for me now! Also, it seems the ci tests passed, so you can probably just go ahead and merge.

**Comment by tischi** [comment]
In fact, we do need the Linux jars:
`java.lang.UnsatisfiedLinkError: Can't load library: /home/runner/work/mobie-viewer-fiji/mobie-viewer-fiji/natives/linux-amd64//libgluegen_rt.so`
I will add them.

**Pull request merged**
