### PR TITLE
Ome zarr workshop 2022

### PR DESCRIPTION
**Pull request by tischi**

### CODE REVIEW

**Comment by tischi** [comment]
@K-Meech Could you have a quick look please whether this could be merged?

**Comment by K-Meech** [comment]
Hi @tischi - I can take a look tomorrow (I'm still on holiday today :)

**Review by K-Meech — APPROVED** [review]
Looks good to me! At some point, it might be nice to also give an estimate of the size (GB) of the screenshots or raster images. Just by using the bitdepth of the image + the maximum number of voxels. This would make it easier for people to tell whether their computer can handle it or not :)

**Comment by tischi** [comment]
@K-Meech Spot on!
This is part of the big master plan :-)
https://github.com/xulman/ome-zarr-fiji-ui/issues/3#issuecomment-1085119657

**Comment by joshmoore** [comment]
@tischi : do you have a list of the datasets that you are intending to demo here?

**Comment by tischi** [comment]
@joshmoore 
1. https://s3.embl.de/i2k-2020/platy-raw.ome.zarr
2. https://uk1s3.embassy.ebi.ac.uk/idr/zarr/v0.1/6001237.zarr
Do you think that's good?
Let's discuss this in the presentation that I just shared with you.

**Pull request merged**
