### PR TITLE
Fix N5 and update bigdataviewer-vistools version

### PR DESCRIPTION
**Pull request by KateMoreva**

### CODE REVIEW

**Comment by tischi** [comment]
@KateMoreva Why did you change the bdv-core dependency? We need this version and we also need that the name of the Source is changed during the transformation.

**Comment by KateMoreva** [comment]
> @KateMoreva Why did you change the bdv-core dependency? We need this version and we also need that the name of the Source is changed during the transformation.

Ok, sorry

**Comment by KateMoreva** [comment]
> > @KateMoreva Why did you change the bdv-core dependency? We need this version and we also need that the name of the Source is changed during the transformation.
> 
> Ok, sorry

Changes were reverted.

**Comment by tischi** [comment]
Thanks!

**Pull request closed without merging**
